import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import DashboardHeader from "@/components/dashboard/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EnginetifAI",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        {session && <DashboardHeader />}
        {children}
        </Provider>
        </body>
    </html>
  );
}
